User.create(first_name: "Ace", last_name: "A", email: "fake", birthday: "01/02/2000", location: "Brooklyn", relationship_goal: "short-term", blood_type: "O", image_url: nil)
User.create(first_name: "Ace", last_name: "B", email: "fake", birthday: "03/04/1999", location: "Rome", relationship_goal: "long-term", blood_type: "A", image_url: nil)
User.create(first_name: "Ace", last_name: "C", email: "fake", birthday: "04/05/1998", location: "Paris", relationship_goal: "short-term", blood_type: "B", image_url: nil)
User.create(first_name: "Bonnie", last_name: "D", email: "fake", birthday: "01/02/1999", location: "Perth", relationship_goal: "long-term", blood_type: "O", image_url: nil)
User.create(first_name: "Bonnie", last_name: "E", email: "fake", birthday: "01/03/1999", location: "Kuala Lumpur", relationship_goal: "short-term", blood_type: "A", image_url: nil)
User.create(first_name: "Bonnie", last_name: "F", email: "fake", birthday: "07/02/2000", location: "Tokyo", relationship_goal: "long-term", blood_type: "B", image_url: nil)
User.create(first_name: "Carl", last_name: "G", email: "fake", birthday: "01/02/2000", location: "Los Angeles", relationship_goal: "short-term", blood_type: "O", image_url: nil)
User.create(first_name: "Carl", last_name: "H", email: "fake", birthday: "02/03/2001", location: "Dayton", relationship_goal: "long-term", blood_type: "A", image_url: nil)
User.create(first_name: "Dope", last_name: "I", email: "fake", birthday: "02/03/2001", location: "Hartford", relationship_goal: "short-term", blood_type: "B", image_url: nil)
User.create(first_name: "Ed", last_name: "J", email: "fake", birthday: "07/02/1996", location: "Detroit", relationship_goal: "long-term", blood_type: "O", image_url: nil)
User.create(first_name: "Edd", last_name: "K", email: "fake", birthday: "08/09/1995", location: "Reno", relationship_goal: "short-term", blood_type: "A", image_url: nil)
User.create(first_name: "Edward", last_name: "L", email: "fake", birthday: "06/07/2000", location: "Montreal", relationship_goal: "long-term", blood_type: "B", image_url: nil)

Message.create(message_text: "a", sender_id: 1, recipient_id: 12)
Message.create(message_text: "b", sender_id: 1, recipient_id: 11)
Message.create(message_text: "c", sender_id: 2, recipient_id: 10)
Message.create(message_text: "d", sender_id: 3, recipient_id: 1)
Message.create(message_text: "e", sender_id: 4, recipient_id: 2)
Message.create(message_text: "f", sender_id: 5, recipient_id: 3)
Message.create(message_text: "g", sender_id: 6, recipient_id: 4)
Message.create(message_text: "h", sender_id: 7, recipient_id: 5)
Message.create(message_text: "i", sender_id: 8, recipient_id: 6)
Message.create(message_text: "j", sender_id: 9, recipient_id: 7)
Message.create(message_text: "k", sender_id: 10, recipient_id: 7)
Message.create(message_text: "l", sender_id: 10, recipient_id: 7)
