User.create(first_name: "Ace", email: "ace1", birthdate: "2000-01-02", location: "Brooklyn", relationship_goal: "short-term", blood_type: "O+", image_url: "http://dybushnell.com/youdoyou_images/m/000603.jpg")
User.create(first_name: "Ace", email: "ace2", birthdate: "1999-01-02", location: "Rome", relationship_goal: "long-term", blood_type: "A+", image_url: "http://dybushnell.com/youdoyou_images/f/000005.jpg")
User.create(first_name: "Ace", email: "ace3", birthdate: "1998-01-02", location: "Paris", relationship_goal: "short-term", blood_type: "B+", image_url: "http://dybushnell.com/youdoyou_images/m/000605.jpg")
User.create(first_name: "Bonnie", email: "bonnie1", birthdate: "1999-01-02", location: "Perth", relationship_goal: "long-term", blood_type: "O+", image_url: "http://dybushnell.com/youdoyou_images/f/000002.jpg")
User.create(first_name: "Bonnie", email: "bonnie2", birthdate: "1999-01-02", location: "Kuala Lumpur", relationship_goal: "short-term", blood_type: "A+", image_url: "http://dybushnell.com/youdoyou_images/f/000004.jpg")
User.create(first_name: "Bonnie", email: "bonnie3", birthdate: "2000-01-02", location: "Tokyo", relationship_goal: "long-term", blood_type: "B+", image_url: "http://dybushnell.com/youdoyou_images/f/000036.jpg")
User.create(first_name: "Alex", email: "alex1", birthdate: "2000-01-02", location: "Los Angeles", relationship_goal: "short-term", blood_type: "O+", image_url: "http://dybushnell.com/youdoyou_images/m/000040.jpg")
User.create(first_name: "Alexa", email: "alexa1", birthdate: "2001-01-02", location: "Dayton", relationship_goal: "long-term", blood_type: "A+", image_url: "http://dybushnell.com/youdoyou_images/f/000041.jpg")
User.create(first_name: "Alexandra", email: "alexandra1", birthdate: "2001-01-02", location: "Hartford", relationship_goal: "short-term", blood_type: "B-", image_url: "http://dybushnell.com/youdoyou_images/f/000028.jpg")
User.create(first_name: "Ed", email: "ed1", birthdate: "1996-01-02", location: "Detroit", relationship_goal: "long-term", blood_type: "O+", image_url: "http://dybushnell.com/youdoyou_images/m/000625.jpg")
User.create(first_name: "Edd", email: "edd1", birthdate: "1995-01-02", location: "Reno", relationship_goal: "short-term", blood_type: "A-", image_url: "http://dybushnell.com/youdoyou_images/m/000613.jpg")
User.create(first_name: "Edward", email: "edward1", birthdate: "2000-01-02", location: "Montreal", relationship_goal: "long-term", blood_type: "B-", image_url: "http://dybushnell.com/youdoyou_images/m/000606.jpg")

Message.create(message_text: "You are ok-looking", sender_id: "ace1", recipient_id: "bonnie1")
Message.create(message_text: "I am sleepy", sender_id: "ace1", recipient_id: "bonnie1")
Message.create(message_text: "Diet Coke is better than water", sender_id: "alex1", recipient_id: "ace1")
Message.create(message_text: "I just want to be held", sender_id: "ace2", recipient_id: "ace1")
Message.create(message_text: "Perhaps pizza?", sender_id: "ace2", recipient_id: "ace3")
Message.create(message_text: "The empitness is consuming", sender_id: "ace3", recipient_id: "ace2")
Message.create(message_text: "WeWork? More like ... [joke here]", sender_id: "ed1", recipient_id: "alex1")
Message.create(message_text: "You are hilarious", sender_id: "alex1", recipient_id: "ed1")
Message.create(message_text: "Yes, tacos", sender_id: "ed1", recipient_id: "ace3")
Message.create(message_text: "Never on Sunday", sender_id: "bonnie1", recipient_id: "alex1")
Message.create(message_text: "I'm a spy", sender_id: "ed1", recipient_id: "alex1")
Message.create(message_text: "Tequila", sender_id: "ed1", recipient_id: "alex1")

Message.create(message_text: "I am become death", sender_id: "ace2", recipient_id: "bonnie1")
Message.create(message_text: "Forever your girl", sender_id: "ace3", recipient_id: "bonnie1")
Message.create(message_text: "Cha cha cha", sender_id: "alex1", recipient_id: "ace2")
Message.create(message_text: "Tango", sender_id: "ace2", recipient_id: "ace3")
Message.create(message_text: "Too many movies about hitmen", sender_id: "ace2", recipient_id: "ace3")
Message.create(message_text: "Mmmm, tungsten carbide drills", sender_id: "ace3", recipient_id: "ace2")
Message.create(message_text: "Soup", sender_id: "ed1", recipient_id: "edward1")
Message.create(message_text: "You are under arrest", sender_id: "alex1", recipient_id: "edd1")
Message.create(message_text: "Kittens", sender_id: "edward1", recipient_id: "edd3")
Message.create(message_text: "Puppies", sender_id: "bonnie1", recipient_id: "bonnie1")
Message.create(message_text: "Snakes", sender_id: "edd1", recipient_id: "alex1")
Message.create(message_text: "Rhino", sender_id: "edward1", recipient_id: "alex1")
